### ISSUE TITLE
macOS 13.0 SDK does not support 10.12 as a deployment target

### ISSUE THREAD

**Issue by coffeebeats** [godotengine/build-containers#124]
It seems that the [latest macOS build containers use the macOS `13.0` SDK](https://github.com/godotengine/build-containers/blob/06cc72f615af8aa042797bdc35ef859c8f19e2cb/Dockerfile.osx#L10). However, according to [Xcode support](https://developer.apple.com/support/xcode), the `13.0` SDK does not support setting the deployment target to `10.12` (`10.13` is the minimum).

The latest Godot version [hard-codes the macOS deployment target to `10.12`](https://github.com/godotengine/godot/blob/24cb43a8741c7b10abbbbc77bb6e2bc188662ce0/platform/macos/detect.py#L117-L124), which seems to be unsupported.

Can the macOS build container be "downgraded" to use an older SDK, `12.3`, which is the latest version that supports `10.12` deployment targets? Alternatively, can Godot drop support for `10.12`?

I'm not sure whether this is actually a problem in practice, as I don't have any real experience building macOS/iOS applications. I'm happy to open a PR to help, but I'm wondering what the preferred solution, if any, would be.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
I guess we can bump target version to 10.13 (or event to 10.15). For Vulkan min. required version, it's 10.15 anyway. OpenGL might work on older versions, but it's not tested. And official support for 10.12 ended in September 2019 (10.15 is the oldest version still receiving security updates).

**Comment by akien-mga** [comment]
I suggest we go with the min version supported by our current SDK, so we gradually phase out EOL platforms as Xcode phases them out too.

So we can go with 10.13 for now, and whenever we need to upgrade Xcode to get the SDK for a newer macOS release, we'll adjust accordingly.

Where can we find info on the oldest supported SDK for a given Xcode release?
