### ISSUE TITLE
Use consistent python version to improve rebuild speeds

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/build-containers#13]
Can we move towards using a consistent python major.minor version across all dockers? 

I build from the same godot source tree mounted in each. Rebuilding a godot platform is greatly sped up by scons tracking what has already been built in `.sconsign.dblite`. 

However, some dockers leave that file in a state that other dockers cannot read. The build dies with `scons: *** [AUTHORS.md] ValueError : unsupported pickle protocol: 4`. Pickle protocol 4 was released in python 3.5. Deleting the db fixes the error but adds on 20+ minutes of build time for rebuilds when it could take 1-2.

**Comment by akien-mga** [comment]
Fixed by godotengine/godot@7f62bed2387db01e825b8d61253619e948c65058.
