### ISSUE TITLE
OSX build error missing MacOSX14.2.sdk.tar.xz

### ISSUE THREAD

**Issue by ajlennon** [godotengine/build-containers#140]
Hi everybody. I'm trying to create some build containers here and getting an error trying to build the OSX container (I have the XCode in there etc. but can't see what I'm doing wrong. Can anybody help? Thanks!

![VirtualBox_Fedora r39_06_05_2024_11_58_16](https://github.com/godotengine/build-containers/assets/1537834/b4a92f78-f26f-4231-8161-283abd7fcc86)

**Comment by ajlennon** [comment]
Trying buidling as root user - same error

**Comment by akien-mga** [comment]
Did you download Xcode 15.2 and place it in `files/Xcode_15.2.xip`?

If yes, does the `logs/xcode_packer.log` log show success, or did something fail?

If everything works as it should, you should have `files/MacOSX14.2.sdk.tar.xz` and `files/iPhoneOS17.2.sdk.tar.xz`. If not, there should be errors in the logs.

**Comment by ajlennon** [comment]
Really odd ownership problem

![VirtualBox_Fedora r39_06_05_2024_15_39_24](https://github.com/godotengine/build-containers/assets/1537834/249904c6-a174-4f9f-a155-419e4fa23afb)

**Comment by ajlennon** [comment]
ok very very very odd there. I changed permissions with no joy. Copied the file to another file then deleted the original and renamed the copy and now the file permissions as OK. not seen that before. Most odd!

**Comment by akien-mga** [comment]
I pushed a small change which should provide a better error message when this happens:
```
Error: 'files/Xcode_15.2.xip' is required for Apple platforms, but was not found or couldn't be read.
It can be downloaded from https://developer.apple.com/download/more/ with a valid apple ID.
```
