### ISSUE TITLE
Is there a reason these images aren't published to a public docker hub repo?

### ISSUE THREAD

**Issue by James-Pickett** [godotengine/build-containers#24]
Hello,

TL;DR Is there a reason these images aren't published to a public docker hub repo?

First of all, thank you and all the contributors for this repo. I wish there was an "ask a question" option instead of opening an issue.

I'm pretty new to linux and containers. I'm wondering if the images built using build.sh contain some kind of security risks or something. Are they safe to push to a public docker hub repo?

Thank you

**Comment by James-Pickett** [comment]
After learning about docker while playing with this project, I realized I don't need to /can't build containers on my box. Docker hub has a free for open source build option.

**Comment by akien-mga** [comment]
Containers like Android, OSX, iOS and UWP should *not* be redistributed, as they contain proprietary SDK for which we don't have redistribution rights.

The others are hosted on a public registry at prehensile-tales.com by @hpvb.

**Comment by tinmanjuggernaut** [comment]
This info should go in the readme.

Do you mean this public registry?
https://registry.prehensile-tales.com/

I see only a build environment and an IDE. I pulled the build environment which downloaded a 600mb blob which turned into a godot/fedora-buildenv image. 

What I was expecting to see in the public registry is to have downloadable images for linux32, linux64, windows, javascript, and the base build. Then android/osx/ios/uwp could be built on top of the base build.
