### ISSUE TITLE
Upgrade Mono containers to 6.12.x with Emscripten 1.39.7+

### ISSUE THREAD

**Issue by akien-mga** [godotengine/build-containers#54]
For Godot 3.2.4+, I plan to upgrade the Mono build containers to a newer branch, probably 6.12.x which is the current Preview branch.

As per https://github.com/godotengine/build-containers/pull/44#issuecomment-609717400, this branch gives us a "known good" version of Emscripten at 1.39.7, which is the oldest version we can use for LTO support (as per https://github.com/godotengine/godot-build-scripts/pull/12).

We can probably backport some patches from Mono's 6.14.x dev branch (which seems to be `master` currently) to get support for a newer Emscripten, as with this rapidly evolving toolchain newer is often better (even if it can mean compat issues). (CC @Faless FYI)

CC @neikeq, anything I should be aware of with regard to Mono 6.12? Will it be seamless for 3.2.3 projects using Mono 6.6.x to upgrade to 3.2.4 with Mono 6.12.x?

**Comment by neikeq** [comment]
>CC @neikeq, anything I should be aware of with regard to Mono 6.12? Will it be seamless for 3.2.3 projects using Mono 6.6.x to upgrade to 3.2.4 with Mono 6.12.x?

None that I know, other than it not being a stable release yet. In the case of wasm though, that may be better considering how bleeding edge it is.

**Comment by akien-mga** [comment]
> None that I know, other than it not being a stable release yet.

I was talking to Mono maintainers yesterday and it seems it could be flagged as stable any time now. They just have an issue as for some reason Linux binaries were not produced for their latest 5.12.x build.

**Comment by akien-mga** [comment]
Fixed by #58.

One last thing we need to do though is include an iOS cross compiler build that matches 6.12 (currently still using the same binary as for 6.6).
