### ISSUE TITLE
iOS container build failure when copying iOS mono cross-compiler

### ISSUE THREAD

**Issue by qjyqjyqjyqjy** [godotengine/build-containers#67]
IOS容器尝试多次，都构建失败了。其他容器都可以构建成功。环境是fedora32。podman2.2.1。

**Comment by akien-mga** [comment]
Please write your issues in English, Godot is an international project and the majority of contributors do not speak Chinese (me included). You can use machine translation tools for that if needed.

**Comment by qjyqjyqjyqjy** [comment]
The iOS container has been tried many times and failed to build.Any other container can be built successfully.The environment is Fedora 32.Podman2.2.1.(Machine translation may not be accurate)

**Comment by akien-mga** [comment]
What is the build issue? It works fine for me.

**Comment by qjyqjyqjyqjy** [comment]
> What is the build issue? It works fine for me.

Is it built in Fedora 32?Could you please provide an environment configuration? I will try to build in the same environment. If it fails, I will give you feedback.

**Comment by akien-mga** [comment]
I'm currently using Fedora 33 as host with Podman 2.2.1, but this upgrade was done only in December, before that we used Fedora 32 and it worked fine too.

**Comment by qjyqjyqjyqjy** [comment]
I chose 6.12.0.111 for the Mono version, which is yours?

**Comment by akien-mga** [comment]
I use 6.12.0.114.

**Comment by qjyqjyqjyqjy** [comment]
> I use 6.12.0.114.

**Comment by qjyqjyqjyqjy** [comment]
STEP 9: RUN mkdir -p /root/aot-compilers/iphone-arm64 &&     tar xvf /root/files/aarch64-apple-darwin-mono-sgen.tar.xz -C /root/aot-compilers/iphone-arm64
tar: /root/files/aarch64-apple-darwin-mono-sgen.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error: error building at STEP "RUN mkdir -p /root/aot-compilers/iphone-arm64 &&     tar xvf /root/files/aarch64-apple-darwin-mono-sgen.tar.xz -C /root/aot-compilers/iphone-arm64": error while running runtime: exit status 2

fedro33 mono6.12.0.114 ....fail...

**Comment by akien-mga** [comment]
I see, that's because this cross-compiler build cannot be made by the container itself so I use a prebuilt one. I should document it indeed.

You can download the `ios-cross-arm64.zip` file from https://github.com/godotengine/godot-mono-builds/releases/tag/release-bda87f2 and then repack it as `aarch64-apple-darwin-mono-sgen.tar.xz` (so unzip, and then archive again as .tar.xz).

I'll try to fix that soon as it's quite confusing and requires manual work.

**Comment by qjyqjyqjyqjy** [comment]
I have been worrying about this problem for many days and it is likely to trouble others. Please fix it. Thank you.
