### ISSUE TITLE
How to get msvc2017.tar

### ISSUE THREAD

**Issue by wangchyz** [godotengine/build-containers#76]
![image](https://user-images.githubusercontent.com/156612/110927180-46a13080-8360-11eb-8cec-69ea9083e67d.png)

**Comment by Xrayez** [comment]
See https://github.com/godotengine/build-containers/issues/74#issuecomment-794228082. You'll need to make sure you have build tools installed (prior to existence of Visual Studio Community). But I couldn't resolve build issues anyway (for some reason, SCons doesn't detect the compiler under wine).

**Comment by hpvb** [comment]
The root of the `msvc2017.tar` should look like this:
```
Microsoft SDKs
Microsoft Visual
Windows Kits
```

**Comment by wangchyz** [comment]
> See [#74 (comment)](https://github.com/godotengine/build-containers/issues/74#issuecomment-794228082) (on a Windows machine). You'll need to make sure you have build tools installed (prior to existence of Visual Studio Community). But I couldn't resolve build issues anyway (for some reason, SCons doesn't detect the compiler under wine).

Thank you，this stackoverflow link is very useful !
