### ISSUE TITLE
If I want to migrate to other projects, can you provide some suggestions?

### ISSUE THREAD

**Issue by zuowanbushiwo** [godotengine/build-containers#94]
This is a very good project, and I have an algorithm library that I plan to handle. But I see that dockerfile has a lot of strong correlations with Godot, so some of them don't understand. <br/>
 I have a C++  based algorithm library, which has no other dependencies, and is compiled based on cmake syntax. I want 
to be able to cross build  and output windows, linux, android (arm64-v8a, armeabi-v7a), macos, ios library binary files on a host
 machine (such as ubuntu 18.04) just like you, then  binary file can be used by its platform applications.<br/>
Are there some simple  project that can be referred to  ？
Thanks！
 Best regards,

**Comment by Calinou** [comment]
To answer: The containers in this repository are highly specific to Godot. These wouldn't be good fits to be converted for general-purpose C/C++ use cases.
